# Generated by Django 5.1.7 on 2025-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(verbose_name="Payment date"),
        ),
    ]
