# Generated by Django 5.1.7 on 2025-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_link_payment_session_id_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(auto_now=True, verbose_name="Payment date"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Card", "Card")],
                default="Card",
                max_length=4,
                verbose_name="Payment mode",
            ),
        ),
    ]
