# Generated by Django 5.1.7 on 2025-03-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="materials/course/preview/%Y/%m/%d/",
                        verbose_name="Saved course preview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="materials/lessons/preview/%Y/%m/%d/",
                        verbose_name="Saved course preview",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["name"],
            },
        ),
    ]
