# Generated by Django 5.1.7 on 2025-03-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="url_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
