name: Django CI

on:
  push:
    branches: [ "yml" ]
  pull_request:
    branches: [ "yml" ]

jobs:
  test:
    runs-on: ubuntu-latest

#    services:
#      # Label used to access the service container
#      postgres:
#        # Docker Hub image
#        image: postgres
#        # Provide the password for postgres
#        env:
#
#          POSTGRES_DB: online_course_project
#          POSTGRES_USER: postgres:16
#          POSTGRES_PASSWORD: library_password
#          POSTGRES_HOST: localhost
#          POSTGRES_PORT: 5432
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#
    - name: Run migrations
      env:
        SECRET_KEY: django-insecure-u_yv*ek#*3y72cy3b9nn+^&0cl!m)f4gwl4vfk!0+&75y^$wh)
        POSTGRES_DB: online_course_project
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: library_password
        POSTGRES_HOST: localhost
      run: python manage.py migrate


#    - name: Run tests
#      run: python manage.py test